<%@ Page Language="C#" MasterPageFile="~/MasterPage/MasterPageHeader.master" Title="Eliminar Usuarios" AutoEventWireup="true" CodeFile="EliminarUsuarios.aspx.cs" Inherits="Paginas_Usuarios_EliminarUsuarios" %>
<%@ Register Src="~/ControlesBase/DialogoError.ascx" TagName="DialogoError" TagPrefix="uc1" %>
<%@ Register Src="~/ControlesBase/MensajeInformacion.ascx" TagName="MensajeInformacion" TagPrefix="uc2" %>
<%@ Register Src="~/ControlesBase/MensajeInformacion.ascx" TagName="MensajeInformacionBotonAceptar" TagPrefix="uc3" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <form id="form1" runat="server">
    <div class="container subnav"> 
			<div class="content"> 
				<div class="sub-heading"> 
					<h2>Usuarios</h2> 
				</div> 
				<div class="subnav-container"> 
				
					<ul id="subnav"> 
  <li><a href="AgregarUsuarios.aspx">Agregar<span></span></a></li> 
  <li><a href="ConsultarUsuarios.aspx">Consultar<span></span></a></li> 
  <li><a href="EliminarUsuarios.aspx" class="active">Eliminar<span></span></a></li> 
  <li><a href="ModificarUsuarios.aspx" >Modificar<span></span></a></li>
</ul> 
						
				</div> 
				
				
				<div class="sub-content"> 
 
        		<div class="features_overview"> 
                 <div class="features_overview_right"> 
                    <h3>Eliminar Usuario</h3>
                                                 <p>Seleccione el usuario a eliminar de la lista</p> 
                       <asp:MultiView ID="uxMultiViewEliminar" runat="server" ActiveViewIndex="0">
                                <asp:View ID="ViewConsultaUsuario" runat="server">

                                    <br />
                                    <table width="70%">
                                        <tr>
                                            <td>Nombre de Usuario:</td>
                                            <td><asp:TextBox ID="uxLogin" runat="server"></asp:TextBox></td>

                                            <td>
                                            <asp:Button ID="uxBotonBuscar" runat="server" Text="Buscar" onclick="uxBotonBuscar_Click"/>
                                        </td>
                                        </tr>
                                        
                                        <tr>
                                            <td>
                                                <uc2:MensajeInformacion ID="uxMensajeInformacion" runat="server" Visible="false" />
                                            </td>
                                        </tr>

                                        <tr>
                                            <td></td>
                                            <td><asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
                                            ControlToValidate="uxLogin" 
                                            ErrorMessage="<%$ Resources:DSU, FaltaNombreUsuario%>" Font-Size="Smaller" Display="Static" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">

                                                <asp:GridView ID="uxConsultaEliminarUsuario" runat="server" AllowPaging="True" DataSourceID="uxObjectConsultaEliminarUsuario"
                                                AutoGenerateColumns="False" DataKeyNames="Login" AutoGenerateDeleteButton="True"
                                                Width="150%" Font-Names="Verdana" Font-Size="Smaller" PageSize="10"
                                                OnSelectedIndexChanging="SelectUsuarios">

                                                    <Columns>

                                                        <asp:BoundField HeaderText="Usuario" DataField="Login" />
                                                        <asp:BoundField HeaderText="Nombre Empleado" DataField="Nombre" />
                                                        <asp:BoundField HeaderText="Apellido Empleado" DataField="Apellido" />  
                                                        <asp:BoundField HeaderText="Status Usuario" DataField="Status" /> 

                                                    </Columns>

                                                    <EmptyDataTemplate>
                                                        <center>
                                                            <span>No hay data cargada </span>
                                                        </center>
                                                    </EmptyDataTemplate>

                                                </asp:GridView>
                                            </td>
                                        </tr>
                                    </table>
                                     <uc3:MensajeInformacionBotonAceptar ID="uxMensajeInformacionBotonAceptar" runat="server" Visible="false" />
                                            
                                </asp:View>
                            </asp:MultiView> 
                            <asp:UpdatePanel ID="up2" runat="server">
                                <ContentTemplate>
                                    <uc1:DialogoError ID="uxDialogoError" runat="server" />
                                </ContentTemplate>
                            </asp:UpdatePanel>
                 </div> 
              </div>
        
				
								</div> 
				
			</div> 
		</div> 
    </form>
    <pp:objectcontainerdatasource runat="server" ID="uxObjectConsultaEliminarUsuario" DataObjectTypeName="Core.LogicaNegocio.Entidades.Usuario" /> 

</asp:Content>
