//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentador {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosPresentadores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosPresentadores() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentador.RecursosPresentadores", typeof(RecursosPresentadores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CON001.
        /// </summary>
        internal static string codigoErrorConsultar {
            get {
                return ResourceManager.GetString("codigoErrorConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEN001.
        /// </summary>
        internal static string codigoErrorGeneral {
            get {
                return ResourceManager.GetString("codigoErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEB001.
        /// </summary>
        internal static string codigoErrorWeb {
            get {
                return ResourceManager.GetString("codigoErrorWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay datos para el parámetro de búsqueda seleccionado.
        /// </summary>
        internal static string MensajeConsulta {
            get {
                return ResourceManager.GetString("MensajeConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario no se encuentra registrado en el sistema.
        /// </summary>
        internal static string MensajeCredenciales {
            get {
                return ResourceManager.GetString("MensajeCredenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un Error Consultando la información..
        /// </summary>
        internal static string mensajeErrorConsultar {
            get {
                return ResourceManager.GetString("mensajeErrorConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un Error no manejado por el sistema..
        /// </summary>
        internal static string mensajeErrorGeneral {
            get {
                return ResourceManager.GetString("mensajeErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un Error en capa Web..
        /// </summary>
        internal static string mensajeErrorWeb {
            get {
                return ResourceManager.GetString("mensajeErrorWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Entidad ya esta registrada en el sistema. Debe ir al módulo Modificar para realizar cualquier operación sobre la misma..
        /// </summary>
        internal static string mensajeRegistroExiste {
            get {
                return ResourceManager.GetString("mensajeRegistroExiste", resourceCulture);
            }
        }
    }
}
