//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DSU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DSU() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DSU", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string ERAnioReportes {
            get {
                return ResourceManager.GetString("ERAnioReportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ^([a-zA-Z](?:(?:(?:\w[\._]?)*)\w)+)([a-zA-Z0-9])$.
        /// </summary>
        internal static string ERLogin {
            get {
                return ResourceManager.GetString("ERLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ^\d{1,7}$.
        /// </summary>
        internal static string ERNumCuentaEmpleado {
            get {
                return ResourceManager.GetString("ERNumCuentaEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ^.*(?=.{6,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&amp;+=]).*$.
        /// </summary>
        internal static string ERPassword {
            get {
                return ResourceManager.GetString("ERPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha egreso debe ser mayor a la fecha de ingreso.
        /// </summary>
        internal static string ErrorFechaEgresoEmpleado {
            get {
                return ResourceManager.GetString("ErrorFechaEgresoEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha fin debe ser mayor a la fecha inicio.
        /// </summary>
        internal static string ErrorFechaFinPropuesta {
            get {
                return ResourceManager.GetString("ErrorFechaFinPropuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario no posee el formato adecuado.
        /// </summary>
        internal static string ErrorFormatoLogin {
            get {
                return ResourceManager.GetString("ErrorFormatoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en en el formato del numero de cuenta (Solo numeros).
        /// </summary>
        internal static string ErrorFormatoNumCuentaEmpleado {
            get {
                return ResourceManager.GetString("ErrorFormatoNumCuentaEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el formato de la contraseña.
        /// </summary>
        internal static string ErrorFormatoPassword {
            get {
                return ResourceManager.GetString("ErrorFormatoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un año.
        /// </summary>
        internal static string FaltaAnioReportes {
            get {
                return ResourceManager.GetString("FaltaAnioReportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir el apellido del contacto.
        /// </summary>
        internal static string FaltaApellidoContacto {
            get {
                return ResourceManager.GetString("FaltaApellidoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir el apellido del empleado.
        /// </summary>
        internal static string FaltaApellidoEmpleado {
            get {
                return ResourceManager.GetString("FaltaApellidoEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir el apellido del receptor de la propuesta.
        /// </summary>
        internal static string FaltaApellidoReceptorPropuesta {
            get {
                return ResourceManager.GetString("FaltaApellidoReceptorPropuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir el apellido del usuario.
        /// </summary>
        internal static string FaltaApellidoUsuario {
            get {
                return ResourceManager.GetString("FaltaApellidoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir el numero de celular del contacto.
        /// </summary>
        internal static string FaltaCelularContacto {
            get {
                return ResourceManager.GetString("FaltaCelularContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir la cedula de identidad del empleado.
        /// </summary>
        internal static string FaltaCIEmpleado {
            get {
                return ResourceManager.GetString("FaltaCIEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir la cedula de identidad para la busqueda.
        /// </summary>
        internal static string FaltaCIFind {
            get {
                return ResourceManager.GetString("FaltaCIFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir la ciudad del cliente.
        /// </summary>
        internal static string FaltaCiudadCliente {
            get {
                return ResourceManager.GetString("FaltaCiudadCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta la contraseña.
        /// </summary>
        internal static string FaltaContrasena {
            get {
                return ResourceManager.GetString("FaltaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir la contraseña del usuario.
        /// </summary>
        internal static string FaltaContrasenaUsuario {
            get {
                return ResourceManager.GetString("FaltaContrasenaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir direccion del cliente.
        /// </summary>
        internal static string FaltaDireccion1Cliente {
            get {
                return ResourceManager.GetString("FaltaDireccion1Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir la fecha de fin de la propuesta.
        /// </summary>
        internal static string FaltaFechaFinPropuesta {
            get {
                return ResourceManager.GetString("FaltaFechaFinPropuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir la fecha de la firma de la propuesta.
        /// </summary>
        internal static string FaltaFechaFirmaPropuesta {
            get {
                return ResourceManager.GetString("FaltaFechaFirmaPropuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir fecha de inicio de la propuesta.
        /// </summary>
        internal static string FaltaFechaInicioPropuesta {
            get {
                return ResourceManager.GetString("FaltaFechaInicioPropuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe Introducir el monto total de la Propuesta.
        /// </summary>
        internal static string FaltaMontoPropuesta {
            get {
                return ResourceManager.GetString("FaltaMontoPropuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir el nombre del cargo.
        /// </summary>
        internal static string FaltaNombreCargo {
            get {
                return ResourceManager.GetString("FaltaNombreCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir el nombre del cliente.
        /// </summary>
        internal static string FaltaNombreCliente {
            get {
                return ResourceManager.GetString("FaltaNombreCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir el nombre del contacto.
        /// </summary>
        internal static string FaltaNombreContacto {
            get {
                return ResourceManager.GetString("FaltaNombreContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir el nombre del empleado.
        /// </summary>
        internal static string FaltaNombreEmpleado {
            get {
                return ResourceManager.GetString("FaltaNombreEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir el nombre del receptor de la propuesta.
        /// </summary>
        internal static string FaltaNombreReceptorPropuesta {
            get {
                return ResourceManager.GetString("FaltaNombreReceptorPropuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir el nombre del usuario.
        /// </summary>
        internal static string FaltaNombreUsuario {
            get {
                return ResourceManager.GetString("FaltaNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir el numero de cuenta del empleado.
        /// </summary>
        internal static string FaltaNumCuentaEmpleado {
            get {
                return ResourceManager.GetString("FaltaNumCuentaEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir un rango de sueldo.
        /// </summary>
        internal static string FaltaRangoSueldo {
            get {
                return ResourceManager.GetString("FaltaRangoSueldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir el R.I.F. del cliente.
        /// </summary>
        internal static string FaltaRIFCliente {
            get {
                return ResourceManager.GetString("FaltaRIFCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir el telefono del cliente.
        /// </summary>
        internal static string FaltaTelefonoCliente {
            get {
                return ResourceManager.GetString("FaltaTelefonoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir el titulo de la propuesta.
        /// </summary>
        internal static string FaltaTituloPropuesta {
            get {
                return ResourceManager.GetString("FaltaTituloPropuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir las horas totales de la propuesta.
        /// </summary>
        internal static string FaltaTotalHorasPropuesta {
            get {
                return ResourceManager.GetString("FaltaTotalHorasPropuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir el nombre de usuario a utilizar.
        /// </summary>
        internal static string FaltaUserName {
            get {
                return ResourceManager.GetString("FaltaUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe introducir la version de la propuesta.
        /// </summary>
        internal static string FaltaVersionPropuesta {
            get {
                return ResourceManager.GetString("FaltaVersionPropuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Usuario:.
        /// </summary>
        internal static string NombreUsuario {
            get {
                return ResourceManager.GetString("NombreUsuario", resourceCulture);
            }
        }
    }
}
