//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3603
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentador {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosPresentadores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosPresentadores() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentador.RecursosPresentadores", typeof(RecursosPresentadores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente modificado con éxito.
        /// </summary>
        internal static string ClienteModificacionExitosa {
            get {
                return ResourceManager.GetString("ClienteModificacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente registrado con éxito.
        /// </summary>
        internal static string ClienteOperacionExitosa {
            get {
                return ResourceManager.GetString("ClienteOperacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CON001.
        /// </summary>
        internal static string codigoErrorConsultar {
            get {
                return ResourceManager.GetString("codigoErrorConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GEN001.
        /// </summary>
        internal static string codigoErrorGeneral {
            get {
                return ResourceManager.GetString("codigoErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ING001.
        /// </summary>
        internal static string codigoErrorIngresar {
            get {
                return ResourceManager.GetString("codigoErrorIngresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WEB001.
        /// </summary>
        internal static string codigoErrorWeb {
            get {
                return ResourceManager.GetString("codigoErrorWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente eliminado con éxito.
        /// </summary>
        internal static string mensajeClienteEliminado {
            get {
                return ResourceManager.GetString("mensajeClienteEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay datos para el parámetro de búsqueda seleccionado.
        /// </summary>
        internal static string MensajeConsulta {
            get {
                return ResourceManager.GetString("MensajeConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Contaco ha sido agregado con exito!.
        /// </summary>
        internal static string MensajeContactoAgregado {
            get {
                return ResourceManager.GetString("MensajeContactoAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe este contacto registrado para un cliente, debe ingresar uno nuevo.
        /// </summary>
        internal static string MensajeContactoExistente {
            get {
                return ResourceManager.GetString("MensajeContactoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario no se encuentra registrado en el sistema.
        /// </summary>
        internal static string MensajeCredenciales {
            get {
                return ResourceManager.GetString("MensajeCredenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Contacto se ha eliminado con exito..
        /// </summary>
        internal static string MensajeEliminarCorrecto {
            get {
                return ResourceManager.GetString("MensajeEliminarCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Contacto no se puede elminar, el Cliente no puede quedar sin Contacto..
        /// </summary>
        internal static string MensajeEliminarFallida {
            get {
                return ResourceManager.GetString("MensajeEliminarFallida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este Empleado ya posee un Usuario.
        /// </summary>
        internal static string mensajeEmpleadoTieneUsuario {
            get {
                return ResourceManager.GetString("mensajeEmpleadoTieneUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un Error Consultando la información..
        /// </summary>
        internal static string mensajeErrorConsultar {
            get {
                return ResourceManager.GetString("mensajeErrorConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un Error tratando de consultar la permisologia.
        /// </summary>
        internal static string mensajeErrorConsultarPermiso {
            get {
                return ResourceManager.GetString("mensajeErrorConsultarPermiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un Error tratando de eliminar..
        /// </summary>
        internal static string mensajeErrorEliminar {
            get {
                return ResourceManager.GetString("mensajeErrorEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un Error no manejado por el sistema..
        /// </summary>
        internal static string mensajeErrorGeneral {
            get {
                return ResourceManager.GetString("mensajeErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un Error Ingresando la información..
        /// </summary>
        internal static string mensajeErrorIngresar {
            get {
                return ResourceManager.GetString("mensajeErrorIngresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un Error trantando de modificar.
        /// </summary>
        internal static string mensajeErrorModificar {
            get {
                return ResourceManager.GetString("mensajeErrorModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un Error en capa Web..
        /// </summary>
        internal static string mensajeErrorWeb {
            get {
                return ResourceManager.GetString("mensajeErrorWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intento fallido. Revise los datos y vuelva a intentar.
        /// </summary>
        internal static string MensajeIniciarSesion {
            get {
                return ResourceManager.GetString("MensajeIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Contacto se modificó con éxito.
        /// </summary>
        internal static string mensajeModificarContacto {
            get {
                return ResourceManager.GetString("mensajeModificarContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Entidad ya esta registrada en el sistema. Debe ir al módulo Modificar para realizar cualquier operación sobre la misma..
        /// </summary>
        internal static string mensajeRegistroExiste {
            get {
                return ResourceManager.GetString("mensajeRegistroExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sesion cerrada por inactividad.
        /// </summary>
        internal static string mensajeSesionTerminada {
            get {
                return ResourceManager.GetString("mensajeSesionTerminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Codigo del Telefono debe ser de 3 digitos y el Numero ser de 7 digitos..
        /// </summary>
        internal static string mensajeTelefonoIncorrecto {
            get {
                return ResourceManager.GetString("mensajeTelefonoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario agregado con exito.
        /// </summary>
        internal static string mensajeUsuarioAgregado {
            get {
                return ResourceManager.GetString("mensajeUsuarioAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario se elimino con exito.
        /// </summary>
        internal static string mensajeUsuarioEliminado {
            get {
                return ResourceManager.GetString("mensajeUsuarioEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario ya existe. Debe intentar con otro nombre de Usuario.
        /// </summary>
        internal static string mensajeUsuarioExiste {
            get {
                return ResourceManager.GetString("mensajeUsuarioExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario ya se encuentra inactivo.
        /// </summary>
        internal static string mensajeUsuarioInactivo {
            get {
                return ResourceManager.GetString("mensajeUsuarioInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario se modifico con exito.
        /// </summary>
        internal static string mensajeUsuarioModificado {
            get {
                return ResourceManager.GetString("mensajeUsuarioModificado", resourceCulture);
            }
        }
    }
}
